sonar.projectKey=catalogo
sonar.projectName=catalogo
sonar.projectVersion=1.0
sonar.sources=app
sonar.sourceEncoding=UTF-8
sonar.python.pylint=true
sonar.python.flake8=true
sonar.exclusions=venv/**/*, .git/**/*, __pycache__/**/*


# Gerar o token e depois colocar em variavel de ambiente.
# token squ_a959506c24fea4dac7b1bd7796177c4f01537e81
SONAR_HOST_URL='http://localhost:9000'