@url=http://127.0.0.1:8000

## Listar todos os produtos do catálogo
GET {{url}}/seller/v1/catalogo?_limit=50&_offset=0

###


#Cadastrar um produto no catalogo
@api_catalogo={{url}}/seller/v1/catalogo

POST {{api_catalogo}}

{
  "seller_id": "Magalu11",
  "sku": "cadeira1",
  "product_name": "cadeira1"
}

###

POST {{api_catalogo}}

{
  "seller_id": "MAaa1",
  "sku": "11111",
  "product_name": "11"
}
###


#Atualizar o nome de um produto
@api_catalogo={{url}}/seller/v1/catalogo

PATCH {{api_catalogo}}/maaa1/11111

{
  "seller_id": "Maaa1",
  "sku": "11111",
  "product_name": "200"
}
###

# Remove produto
DELETE {{api_catalogo}}/Magalu11/cadeira1

###