services:
  app:
    build:
      context: ..
      dockerfile: devtools/Dockerfile
    container_name: catalogo
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/catalogo
    # working_dir: /catalogo
    env_file:
      - ../.env
    restart: unless-stopped